version: "3"

services:
    php:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - .:/var/www/html
      working_dir: /var/www/html
      tty: true
      ports:
          - "8080:80"