version: "3"

services:
  psr-jwt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
    working_dir: /var/www/html
    tty: true
    ports:
        - "8080:8080"
  curl:
    image: php:7.2
    volumes:
        - ./curl:/var/www/html
    working_dir: /var/www/html
    tty: true
    ports:
        - "8888:8888"